"""Recovering albums and favourites from Photos.sqlite (a separate feature).

Entirely independent of the backup: it reads the device's Photos database
(`/PhotoData/Photos.sqlite`, readable over AFC depending on the iOS version —
check with `--probe-albums`), parses it LOCALLY and materialises the albums as
COPIES of the already-backed-up files: ordinary files, movable anywhere, at
the price of disk space (a deliberate trade-off — hard links, tried first,
required too many usage precautions). It never modifies the backup, and its
failure blocks nothing.

Defences (the Photos.sqlite schema is undocumented and changes with each iOS):
- copy the database plus its -wal journal, then PRAGMA quick_check BEFORE any
  parsing; a doubtful copy is retried once, then fails loudly;
- no join-table name hard-coded: the Z_xxASSETS table is discovered by
  introspection and VALIDATED by an actual join;
- any expected column missing raises AlbumsSchemaError naming what was found
  versus what was expected, never a silently empty result;
- _Albums/ is only regenerated when it carries the "generated by AppleSync"
  marker; a hand-made _Albums is never touched.
"""

from __future__ import annotations

import csv
import os
import shutil
import sqlite3
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional

from applesync.core.manifest import Manifest
from applesync.device.base import DeviceSession

PHOTOS_DB = "/PhotoData/Photos.sqlite"
USER_ALBUM_KIND = 2          # ZGENERICALBUM.ZKIND of user-created albums
CHUNK = 1024 * 1024
ALBUMS_DIRNAME = "_Albums"
FAVORITES_DIRNAME = "_Favorites"
MARKER = ".applesync-generated"

# Zones of the photo library covered by the backup (see device/afc.py).
COVERED_ZONES = {"DCIM", "PhotoData/CPLAssets", "PhotoData/PhotoCloudSharingData"}


class AlbumsError(Exception):
    """Album recovery impossible — does not affect the backup."""


class AlbumsSchemaError(AlbumsError):
    """The Photos.sqlite schema does not match what is expected (an iOS
    change, most likely). The message names what was found, for diagnosis."""


@dataclass
class AlbumsData:
    """What was extracted from the database: user albums and favourites.

    Paths are inventory paths ("100APPLE/IMG_0001.HEIC")."""

    albums: list[tuple[str, list[str]]] = field(default_factory=list)
    favorites: list[str] = field(default_factory=list)
    ignored_assets: list[tuple[str, str]] = field(default_factory=list)  # (asset, reason)
    # Census of the WHOLE library (not just albums) by storage zone: the zones
    # in COVERED_ZONES are backed up, anything else is NOT.
    library_by_zone: dict[str, int] = field(default_factory=dict)


@dataclass
class AlbumsReport:
    albums_count: int = 0
    copies_created: int = 0
    copied_bytes: int = 0
    favorites_count: int = 0
    csv_path: str = ""
    unmatched: list[tuple[str, str, str]] = field(default_factory=list)  # (album, file, reason)
    warnings: list[str] = field(default_factory=list)
    library_by_zone: dict[str, int] = field(default_factory=dict)

    def to_markdown(self) -> str:
        from applesync.core.report import fmt_bytes

        lines = [
            "# Albums recovered from the device",
            "",
            f"- Albums: **{self.albums_count}** (in `{ALBUMS_DIRNAME}/`)",
            f"- Files copied: {self.copies_created} — {fmt_bytes(self.copied_bytes)} "
            f"of disk space used",
            f"- Favourites: {self.favorites_count} "
            f"(in `{ALBUMS_DIRNAME}/{FAVORITES_DIRNAME}/`)",
            f"- Full detail: `{self.csv_path}`",
            "",
        ]
        if self.library_by_zone:
            outside = sum(
                n for z, n in self.library_by_zone.items() if z not in COVERED_ZONES
            )
            lines.append("## Where the library files live")
            lines.append("")
            for zone, n in sorted(self.library_by_zone.items(), key=lambda x: -x[1]):
                if zone in COVERED_ZONES:
                    lines.append(f"- `{zone}`: {n} — **covered by the backup** ✓")
                else:
                    lines.append(f"- `{zone}`: {n} — **NOT covered by the backup** ⚠")
            lines.append("")
            if outside:
                lines.append(
                    f"⚠ **{outside} library item(s) live in an uncovered zone**: "
                    f"they show up in the Photos app but are not in the backup. "
                    f"Worth reporting so it can be addressed."
                )
            else:
                lines.append(
                    "Every zone where the library lives is covered by the backup."
                )
            lines.append("")
        if self.warnings:
            lines.append("## Warnings")
            lines.append("")
            lines.extend(f"- {w}" for w in self.warnings)
            lines.append("")
        if self.unmatched:
            lines.append(f"## Unmatched items: {len(self.unmatched)}")
            lines.append("")
            lines.append("Present in an album on the device but not found in the")
            lines.append("backup (never synchronised, or outside the covered zones):")
            lines.append("")
            lines.extend(
                f"- `{f}` (album \"{a}\") — {r}" for a, f, r in self.unmatched
            )
            lines.append("")
        if not self.unmatched:
            lines.append("No discrepancy: every album item points at a file of the")
            lines.append("backup.")
        return "\n".join(lines)


ProgressCb = Callable[[int, int], None]     # (done, total)


# ---------------------------------------------------------------------------
# 1. Fetching the database
# ---------------------------------------------------------------------------

def _fetch_one(session: DeviceSession, remote: str, target: Path,
               progress_cb: Optional[ProgressCb], base_done: int, total: int,
               cancel: Optional[Callable[[], bool]] = None) -> int:
    size = session.stat_media(remote)
    part = target.with_name(target.name + ".part")
    done = 0
    with session.open_media(remote) as reader, open(part, "wb") as out:
        while done < size:
            if cancel is not None and cancel():
                raise AlbumsError("album recovery interrupted")
            data = reader.read(min(CHUNK, size - done))
            if not data:
                raise AlbumsError(
                    f"{remote}: stream ended at {done} bytes, {size} expected"
                )
            out.write(data)
            done += len(data)
            if progress_cb:
                progress_cb(base_done + done, total)
        out.flush()
        os.fsync(out.fileno())
    os.replace(part, target)
    return size


def fetch_photos_db(
    session: DeviceSession,
    work_dir: Path,
    progress_cb: Optional[ProgressCb] = None,
    cancel: Optional[Callable[[], bool]] = None,
    phase_cb: Optional[Callable[[str], None]] = None,
) -> Path:
    """Copy Photos.sqlite (plus its -wal journal if any) and check integrity.

    Two attempts: the database may be mid-write on the device while we copy.
    After that: fail loudly."""
    work_dir = Path(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)

    last_error = "?"
    for _attempt in (1, 2):
        total = session.stat_media(PHOTOS_DB)
        wal_size = 0
        try:
            wal_size = session.stat_media(PHOTOS_DB + "-wal")
        except Exception:
            wal_size = 0
        total += wal_size

        db_local = work_dir / "Photos.sqlite"
        # A stale -shm/-wal from a previous copy would corrupt the open.
        for suffix in ("-wal", "-shm"):
            (work_dir / ("Photos.sqlite" + suffix)).unlink(missing_ok=True)

        done = _fetch_one(session, PHOTOS_DB, db_local, progress_cb, 0, total,
                          cancel=cancel)
        if wal_size:
            try:
                _fetch_one(session, PHOTOS_DB + "-wal",
                           work_dir / "Photos.sqlite-wal",
                           progress_cb, done, total, cancel=cancel)
            except Exception:
                if cancel is not None and cancel():
                    raise
                # WAL gone or changed between the stat and the read: the
                # database alone stays consistent (state before the last
                # writes).
                (work_dir / "Photos.sqlite-wal").unlink(missing_ok=True)

        if phase_cb:
            phase_cb("Integrity check on the copied database…")
        try:
            con = sqlite3.connect(f"file:{db_local}?mode=ro", uri=True)
            try:
                verdict = con.execute("PRAGMA quick_check").fetchone()[0]
            finally:
                con.close()
            if verdict == "ok":
                return db_local
            last_error = f"quick_check: {verdict}"
        except sqlite3.Error as e:
            last_error = f"cannot open: {e}"

    raise AlbumsError(
        f"Photos.sqlite copied twice, neither copy is sound ({last_error}). "
        f"Try again with the device idle and the Photos app closed."
    )


# ---------------------------------------------------------------------------
# 2. Defensive parsing
# ---------------------------------------------------------------------------

def _require_columns(con: sqlite3.Connection, table: str, needed: set[str]) -> None:
    try:
        cols = {r[1] for r in con.execute(f'PRAGMA table_info("{table}")')}
    except sqlite3.Error as e:
        raise AlbumsSchemaError(f"table {table} unreadable: {e}") from e
    if not cols:
        raise AlbumsSchemaError(f"table {table} missing from Photos.sqlite")
    missing = needed - cols
    if missing:
        raise AlbumsSchemaError(
            f"{table}: expected columns missing {sorted(missing)} — iOS schema "
            f"changed? Columns found: {sorted(cols)[:20]}…"
        )


def _find_join_table(con: sqlite3.Connection) -> tuple[str, str, str]:
    """Discover the albums<->assets join table (its name varies by iOS).

    A candidate is a Z_%ASSETS table with one *ALBUMS and one *ASSETS column;
    it is validated by an actual join on ZGENERICALBUM and ZASSET."""
    candidates: list[tuple[str, str, str]] = []
    rows = con.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name LIKE 'Z^_%ASSETS' ESCAPE '^'"
    ).fetchall()
    for (name,) in rows:
        cols = [r[1] for r in con.execute(f'PRAGMA table_info("{name}")')]
        album_col = next((c for c in cols if c.upper().endswith("ALBUMS")), None)
        asset_col = next(
            (c for c in cols if c.upper().endswith("ASSETS") and c != album_col), None
        )
        if album_col and asset_col:
            candidates.append((name, album_col, asset_col))

    if not candidates:
        raise AlbumsSchemaError(
            "no albums<->assets join table recognised (Z_%ASSETS) — "
            f"tables seen: {[r[0] for r in rows]}"
        )

    validated = []
    for name, album_col, asset_col in candidates:
        try:
            n = con.execute(
                f'SELECT COUNT(*) FROM "{name}" j'
                f' JOIN ZGENERICALBUM g ON g.Z_PK = j."{album_col}"'
                f' JOIN ZASSET s ON s.Z_PK = j."{asset_col}"'
            ).fetchone()[0]
        except sqlite3.Error:
            continue
        validated.append((n, name, album_col, asset_col))

    if not validated:
        raise AlbumsSchemaError(
            f"candidate tables found but none joins ZGENERICALBUM and ZASSET: "
            f"{[c[0] for c in candidates]}"
        )
    validated.sort(reverse=True)          # the most populated one wins
    _, name, album_col, asset_col = validated[0]
    return name, album_col, asset_col


def _asset_rel_path(
    directory: Optional[str], filename: Optional[str]
) -> tuple[Optional[str], str]:
    """(inventory path, reason when unusable).

    Covered zones: DCIM (relative paths) and the PhotoData zones (paths
    prefixed with the zone name, exactly as in the inventory)."""
    if not filename:
        return None, "empty file name in the database"
    d = (directory or "").strip("/")
    if d.startswith("DCIM/"):
        return f"{d[5:]}/{filename}", ""
    if (d.startswith("PhotoData/CPLAssets/") or d == "PhotoData/CPLAssets"
            or d.startswith("PhotoData/PhotoCloudSharingData/")
            or d == "PhotoData/PhotoCloudSharingData"):
        return f"{d[len('PhotoData/'):]}/{filename}", ""
    if d.startswith("DCIM"):
        return None, f"unexpected folder \"{directory}\""
    if not d:
        return None, "outside covered zones (empty folder)"
    return None, f"outside covered zones (\"{directory}\")"


def parse_albums(db_path: Path) -> AlbumsData:
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        _require_columns(con, "ZASSET",
                         {"Z_PK", "ZDIRECTORY", "ZFILENAME", "ZFAVORITE",
                          "ZTRASHEDSTATE"})
        _require_columns(con, "ZGENERICALBUM",
                         {"Z_PK", "ZTITLE", "ZKIND", "ZTRASHEDSTATE"})
        join, album_col, asset_col = _find_join_table(con)

        data = AlbumsData()

        rows = con.execute(
            f'SELECT g.Z_PK, g.ZTITLE, s.ZDIRECTORY, s.ZFILENAME'
            f' FROM "{join}" j'
            f' JOIN ZGENERICALBUM g ON g.Z_PK = j."{album_col}"'
            f' JOIN ZASSET s ON s.Z_PK = j."{asset_col}"'
            f' WHERE g.ZKIND = ? AND IFNULL(g.ZTRASHEDSTATE, 0) = 0'
            f'   AND IFNULL(s.ZTRASHEDSTATE, 0) = 0',
            (USER_ALBUM_KIND,),
        ).fetchall()

        by_album: dict[tuple[int, str], list[str]] = {}
        for pk, title, directory, filename in rows:
            key = (pk, title or f"(untitled) #{pk}")
            rel, reason = _asset_rel_path(directory, filename)
            if rel is None:
                data.ignored_assets.append((f"{directory}/{filename}", reason))
                by_album.setdefault(key, [])
                continue
            by_album.setdefault(key, []).append(rel)

        # Empty albums are kept (the user will see them); alphabetical order.
        data.albums = sorted(
            ((title, sorted(files)) for (_, title), files in by_album.items()),
            key=lambda x: x[0].casefold(),
        )

        for directory, filename in con.execute(
            "SELECT ZDIRECTORY, ZFILENAME FROM ZASSET"
            " WHERE ZFAVORITE = 1 AND IFNULL(ZTRASHEDSTATE, 0) = 0"
        ):
            rel, reason = _asset_rel_path(directory, filename)
            if rel is None:
                data.ignored_assets.append((f"{directory}/{filename}", reason))
            else:
                data.favorites.append(rel)
        data.favorites.sort()

        # Full census: where do the library files actually live?
        # Zone = first levels of the path (DCIM, PhotoData/CPLAssets, …).
        for (directory,) in con.execute(
            "SELECT ZDIRECTORY FROM ZASSET WHERE IFNULL(ZTRASHEDSTATE, 0) = 0"
        ):
            d = (directory or "").strip("/")
            if d.startswith("DCIM"):
                zone = "DCIM"
            elif not d:
                zone = "(empty folder)"
            else:
                parts = d.split("/")
                zone = "/".join(parts[:2]) if len(parts) >= 2 else parts[0]
            data.library_by_zone[zone] = data.library_by_zone.get(zone, 0) + 1
        return data
    finally:
        con.close()


# ---------------------------------------------------------------------------
# 3. Materialisation
# ---------------------------------------------------------------------------

_FORBIDDEN = '<>:"/\\|?*'
_CSV_HEADER = "album;backup_file;device_source"


def _generated_by_us(root: Path) -> bool:
    """Is this _Albums folder one of ours?

    The marker comes first; failing that, our own albums.csv is proof enough
    (the marker can vanish if a rebuild was interrupted by a locked file,
    typically the CSV left open in a spreadsheet)."""
    if (root / MARKER).exists():
        return True
    csv_file = root / "albums.csv"
    if csv_file.exists():
        try:
            with open(csv_file, encoding="utf-8-sig") as fh:
                return fh.readline().strip() == _CSV_HEADER
        except OSError:
            return False
    return False


def _sanitize(name: str) -> str:
    clean = "".join("_" if c in _FORBIDDEN or ord(c) < 32 else c for c in name)
    clean = clean.strip(" .")
    return clean or "_album"


def _latest_local(manifest: Manifest, rel: str) -> Optional[str]:
    entries = manifest.entries_for_path(rel)
    if not entries:
        return None
    return max(entries, key=lambda e: e.synced_at).local_path


def materialize_albums(
    data: AlbumsData,
    manifest: Manifest,
    dest_root: Path,
    progress_cb: Optional[ProgressCb] = None,   # (files done, files total)
) -> AlbumsReport:
    """(Re)generate `_Albums/`: one folder per album holding COPIES of the
    backup files (ordinary files), plus `_Favorites/` and a summary CSV.

    `_Albums/` is only wiped and rebuilt when it carries the "generated by
    AppleSync" marker — a hand-made folder is never touched."""
    dest_root = Path(dest_root)
    root = dest_root / ALBUMS_DIRNAME
    marker = root / MARKER
    if root.exists():
        if not _generated_by_us(root):
            raise AlbumsError(
                f"{ALBUMS_DIRNAME}/ exists but does not look like a folder "
                f"generated by AppleSync — to be safe, move it or delete it "
                f"yourself, then click \"Albums\" again."
            )
        try:
            shutil.rmtree(root)
        except OSError as e:
            # Locked file (albums.csv open in a spreadsheet?): re-mark the
            # folder as ours for the next attempt, and explain.
            try:
                if root.exists():
                    marker.write_text("generated by AppleSync\n", encoding="utf-8")
            except OSError:
                pass
            raise AlbumsError(
                f"Cannot rebuild {ALBUMS_DIRNAME}/: one of its files is open in "
                f"another program (albums.csv in a spreadsheet?). Close it and "
                f"click \"Albums\" again. Detail: {e}"
            ) from e
    root.mkdir(parents=True)
    marker.write_text(
        "Folder generated by AppleSync (copies of the backup files).\n"
        "Rebuilt on every album recovery: do not store anything here.\n",
        encoding="utf-8",
    )

    report = AlbumsReport(albums_count=len(data.albums),
                          favorites_count=len(data.favorites),
                          library_by_zone=dict(data.library_by_zone))

    def copy_into(folder: Path, rel_local: str) -> int:
        """Copy a backup file into the album folder. Returns bytes written."""
        src = dest_root / rel_local
        base = Path(rel_local).name
        dst = folder / base
        n = 2
        while dst.exists():
            p = Path(base)
            dst = folder / f"{p.stem}.~{n}{p.suffix}"
            n += 1
        shutil.copy2(src, dst)
        return dst.stat().st_size

    groups: list[tuple[str, str, list[str]]] = [
        (title, _sanitize(title), files) for title, files in data.albums
    ]
    groups.append(("Favourites", FAVORITES_DIRNAME, data.favorites))
    expected_total = sum(len(files) for _, _, files in groups)
    done = 0

    csv_path = root / "albums.csv"
    with open(csv_path, "w", newline="", encoding="utf-8-sig") as fh:
        w = csv.writer(fh, delimiter=";")
        w.writerow(["album", "backup_file", "device_source"])

        seen: set[str] = set()
        for title, folder_name, files in groups:
            folder = root / folder_name
            n = 2
            while folder.name in seen:
                folder = root / f"{folder_name}~{n}"
                n += 1
            seen.add(folder.name)
            folder.mkdir(parents=True, exist_ok=True)

            for rel in files:
                done += 1
                if progress_cb:
                    progress_cb(done, expected_total)
                local = _latest_local(manifest, rel)
                if local is None:
                    report.unmatched.append(
                        (title, rel, "never synchronised (run a sync first)")
                    )
                    continue
                if not (dest_root / local).exists():
                    report.unmatched.append(
                        (title, rel, f"absent from disk ({local}) — check the destination")
                    )
                    continue
                w.writerow([title, local, rel])
                report.copied_bytes += copy_into(folder, local)
                report.copies_created += 1

        for asset, reason in data.ignored_assets:
            w.writerow(["(ignored)", "", f"{asset} — {reason}"])

    if data.ignored_assets:
        report.warnings.append(
            f"{len(data.ignored_assets)} database item(s) ignored (outside the "
            f"covered zones) — listed at the end of the CSV."
        )
    report.csv_path = str(csv_path)
    return report


def save_report(report: AlbumsReport, dest_root: Path) -> Path:
    out_dir = Path(dest_root) / ".applesync" / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"albums_{time.strftime('%Y%m%d-%H%M%S')}.md"
    path.write_text(report.to_markdown(), encoding="utf-8")
    return path
